=== GiedriusMauza/LibraryManagementSystem/1.1 Part/library_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library" type="libraryType"/>
  <xs:complexType name="librarianType">
    <xs:sequence>
      <xs:element type="xs:string" name="librarian-id"/>
      <xs:element type="xs:string" name="librarian-email"/>
      <xs:element type="xs:string" name="librarian-name"/>
      <xs:element type="xs:string" name="last-name"/>
      <xs:element type="xs:string" name="phoneNumber"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="item-id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="author">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Edmundas Untulis"/>
            <xs:enumeration value="Jurga Tumasonytė"/>
            <xs:enumeration value="Virginija Kulvinskaitė"/>
            <xs:enumeration value="Saulius Šaltenis"/>
            <xs:enumeration value="Balys Sruoga"/>
            <xs:enumeration value="Darius Musteikis"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="copies-number">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="3"/>
            <xs:enumeration value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="production-year">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2023"/>
            <xs:enumeration value="2022"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="publisher">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Eglės leidykla"/>
            <xs:enumeration value="Lietuvos rašytojų sąjungos leidykla"/>
            <xs:enumeration value="Kitos knygos"/>
            <xs:enumeration value="Vaga"/>
            <xs:enumeration value="Baltos lankos"/>
            <xs:enumeration value="Darius Musteikis"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="status"/>
      <xs:element name="title">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Žvilgsnis iš maišo"/>
            <xs:enumeration value="Naujagimiai"/>
            <xs:enumeration value="Keturi"/>
            <xs:enumeration value="Akis į akį. Klaipėda 1923"/>
            <xs:enumeration value="Dievų miškas"/>
            <xs:enumeration value="Mėguvos Valdovas"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="borrowingType">
    <xs:sequence>
      <xs:element name="borrowing-id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="borrow-date">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2022-10-14"/>
            <xs:enumeration value="2021-11-14"/>
            <xs:enumeration value="2021-10-14"/>
            <xs:enumeration value="2021-10-04"/>
            <xs:enumeration value="2023-01-14"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="return-date">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2022-11-25"/>
            <xs:enumeration value="2022-12-16"/>
            <xs:enumeration value="2023-06-26"/>
            <xs:enumeration value="2023-02-09"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="itemType" name="item"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="borrowingsType">
    <xs:sequence>
      <xs:element type="borrowingType" name="borrowing" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="subscriberType">
    <xs:sequence>
      <xs:element name="subscriber-id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="subscriber-name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Jonas"/>
            <xs:enumeration value="Benas"/>
            <xs:enumeration value="Ona"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="subscriber-last-name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Jonaitis"/>
            <xs:enumeration value="Petraitis"/>
            <xs:enumeration value="Onauskienė"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="address">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Kalno g. 18"/>
            <xs:enumeration value="Pakalnės g. 44"/>
            <xs:enumeration value="Piles g. 21"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="email">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="jonas@email.ff"/>
            <xs:enumeration value="benas@email.ff"/>
            <xs:enumeration value="ona@email.ff"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="phone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="+3706712333"/>
            <xs:enumeration value="+3706715124"/>
            <xs:enumeration value="+370675555"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="borrowingsType" name="borrowings"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="subscribersType">
    <xs:sequence>
      <xs:element type="subscriberType" name="subscriber" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="libraryType">
    <xs:sequence>
      <xs:element type="xs:string" name="library-id"/>
      <xs:element type="xs:string" name="library-address"/>
      <xs:element type="xs:string" name="library-name"/>
      <xs:element type="xs:string" name="work-hours"/>
      <xs:element type="librarianType" name="librarian"/>
      <xs:element type="subscribersType" name="subscribers"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GiedriusMauza/LibraryManagementSystem/1.1 Part/library_XSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="library_XSD.xsd">
    <library-id>1</library-id>
    <library-address>Gedimino pr. 20</library-address>
    <library-name>Mazvydo</library-name>
    <work-hours>14-16</work-hours>
    <librarian>
		<librarian-id>1</librarian-id>
        <librarian-email>petras@email.ff</librarian-email>
		<librarian-name>Petras</librarian-name>
        <last-name>Petraitis</last-name>        
        <phoneNumber>+370671124124</phoneNumber>
    </librarian>
    <subscribers>
        <subscriber>
            <subscriber-id>1</subscriber-id>
            <subscriber-name>Jonas</subscriber-name>
            <subscriber-last-name>Jonaitis</subscriber-last-name>
            <address>Kalno g. 18</address>
            <email>jonas@email.ff</email>
            <phone>+3706712333</phone>
            <borrowings>
                <borrowing>
                    <borrowing-id>1</borrowing-id>
                    <borrow-date>2022-10-14</borrow-date>
                    <return-date>2022-11-25</return-date>
                    <item>
						<item-id>1</item-id>
                        <author>Edmundas Untulis</author>
                        <copies-number>3</copies-number>                        
                        <production-year>2023</production-year>
                        <publisher>Eglės leidykla</publisher>
                        <status>true</status>
                        <title>Žvilgsnis iš maišo</title>
                    </item>
                </borrowing>
                <borrowing>
				    <borrowing-id>2</borrowing-id>
                    <borrow-date>2021-11-14</borrow-date>
					<return-date>2022-11-25</return-date>
                    <item>
					    <item-id>2</item-id>
                        <author>Jurga Tumasonytė</author>
                        <copies-number>1</copies-number>
                        <production-year>2022</production-year>
                        <publisher>Lietuvos rašytojų sąjungos leidykla</publisher>
                        <status>true</status>
                        <title>Naujagimiai</title>
                    </item>
                </borrowing>
            </borrowings>
        </subscriber>
        <subscriber>
            <subscriber-id>2</subscriber-id>
            <subscriber-name>Benas</subscriber-name>
            <subscriber-last-name>Petraitis</subscriber-last-name>
            <address>Pakalnės g. 44</address>
            <email>benas@email.ff</email>
            <phone>+3706715124</phone>
            <borrowings>
                <borrowing>
					<borrowing-id>1</borrowing-id>
                    <borrow-date>2021-10-14</borrow-date>
                    <return-date>2022-12-16</return-date>
                    <item>
                        <item-id>1</item-id>
                        <author>Virginija Kulvinskaitė</author>
                        <copies-number>3</copies-number>
                        <production-year>2023</production-year>
                        <publisher>Kitos knygos</publisher>
                        <status>true</status>
                        <title>Keturi</title>
                    </item>                    
                </borrowing>
            </borrowings>
        </subscriber>
        <subscriber>
            <subscriber-id>3</subscriber-id>
            <subscriber-name>Ona</subscriber-name>
            <subscriber-last-name>Onauskienė</subscriber-last-name>
            <address>Piles g. 21</address>
            <email>ona@email.ff</email>
            <phone>+370675555</phone>
            <borrowings>
                <borrowing>
                    <borrowing-id>1</borrowing-id>
                    <borrow-date>2022-10-14</borrow-date>
                    <return-date>2022-11-25</return-date>
                    <item>
					    <item-id>1</item-id>
                        <author>Saulius Šaltenis</author>
                        <copies-number>3</copies-number>
                        <production-year>2023</production-year>
                        <publisher>Vaga</publisher>
                        <status>true</status>
                        <title>Akis į akį. Klaipėda 1923</title>
                    </item>
                </borrowing>
                <borrowing>
				    <borrowing-id>2</borrowing-id>
                    <borrow-date>2021-10-04</borrow-date>
                    <return-date>2023-06-26</return-date>
                    <item>
					    <item-id>2</item-id>
                        <author>Balys Sruoga</author>
                        <copies-number>1</copies-number>
                        <production-year>2022</production-year>
                        <publisher>Baltos lankos</publisher>
                        <status>true</status>
                        <title>Dievų miškas</title>
                    </item>
                </borrowing>
                <borrowing>
				    <borrowing-id>3</borrowing-id>
                    <borrow-date>2023-01-14</borrow-date>
                    <return-date>2023-02-09</return-date>
                    <item>
					    <item-id>3</item-id>
                        <author>Darius Musteikis</author>
                        <copies-number>1</copies-number>
                        <production-year>2022</production-year>
                        <publisher>Darius Musteikis</publisher>
                        <status>true</status>
                        <title>Mėguvos Valdovas</title>
                    </item>                   
                </borrowing>
            </borrowings>
        </subscriber>
    </subscribers>
</library>
